COMANDO_CAMINO = "camino"
COMANDO_IMPORTANTES = "mas_importantes"
COMANDO_RECOMENDACION = "recomendacion"
COMANDO_CICLO = "ciclo"
COMANDO_RANGO = "rango"
COMANDOS = {COMANDO_CAMINO, COMANDO_IMPORTANTES, COMANDO_RECOMENDACION, COMANDO_CICLO, COMANDO_RANGO}


SEPARADOR_CANCIONES = " >>>> "


GRUPO_CANCIONES = "canciones"
GRUPO_USUARIOS = "usuarios"
GRUPO_PLAYLISTS = "playlists"
